name: "sign checker"
description: "check sign"
inputs:
  pr_sha:
    required: true
    description: PR SHA
  pr_num:
    required: true
    description: PR Number
  github_token:
    required: true
    description: Github Token
  changed_files:
    required: true
    description: Changed Filenames
  subscan_apikey:
    required: true
    description: Subscan API Key for verify owner
outputs:
  verified:
    description: Verified Status
    value: ${{ steps.executor.outputs.verified }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Running on the default branch.
      if: steps.branch-name.outputs.is_default == 'true'
      run: |
        echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
      # Outputs: "Running on default: main".

    - name: Running on a pull request branch.
      if: steps.branch-name.outputs.is_default == 'false'
      run: |
        echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"
    - uses: actions/cache@v3
      id: cache-dist
      with:
        path: main.js
        key: ${{ hashFiles('**/**') }}
    - run: |
        bash -c "env | sort"
        echo -------------
      shell: bash
    - run: |
        cd ${{ github.action_path }}
        if [[ ! -d dist ]]; then
          npm install -g yarn
          yarn && yarn build
        fi;
      shell: bash
    - run: node ${{ github.action_path }}/main.js
      shell: bash
      id: executor
      env:
        INPUT_SHA: ${{ inputs.pr_sha }}
        INPUT_NUM: ${{ inputs.pr_num }}
        INPUT_TOKEN: ${{ inputs.github_token }}
        INPUT_CHANGED_FILES: ${{ inputs.changed_files }}
        INPUT_APIKEY: ${{ inputs.subscan_apikey }}
